(* Interfaces *)
interface_decl = 'interface' identifier '=' interface_block;
interface_block = '{' i_body '}';

i_body = '{' [{ i_kvp ^+ ',' }]
i_kvp = identifier ['?'] ':' i_value_type
i_value_type = 'string' (* more to come *)


(* 

    ======== ======= =====
    Resource Classes (RCs) 
    ======== ======= =====
    
*)

resource_class = rc_declaration '{' rc_body '}' ;

(* 
    RCs can have generic params (general.ebnf) or flags. 
*)
rc_ident        = identifier rc_params           ;
rc_params       = [generic_params | rc_flags]    ;
rc_flags        = never; 
(* rc_flags =     '(' {identifier ^+ ',' } ')'   ;       *)
(* 👆 that's coming later! *)

(* Title line *)
(*  
    `rc_ident`:
        Must have an identifier.
        If it is not an extension, it may have generics and flags.  
        If it is an extension, it may not have generics nor flags, but the extended RC may. 

    So we could use something like this grammar
        rc_declaration  = 'resource' identifier rc_modification ;
        rc_modification = 'extends' rc_ident | rc_params; 
    to prevent it grammatically,
    but instead I'll opt to take the lazy route and just have it be a semantic error instead 
*)
rc_declaration = 'resource' rc_ident; 


rc_metaclass =  '@empty' | '@media' | '@self';
rc_type_expression = rc_metaclass | type; 


(* 
    -- ----
    RC Body
    -- ----
*)
rc_body = [{ rc_data | rc_interface | rc_links | rc_method }] ;
(* SEMANTICS: Only one of each.  It's just like this so it can be in any order *)



rc_data = 'data' type ;
rc_embed = 'embed' type; 
rc_interface = 'interface' (identifier | interface_block) ; 

rc_links    = 'links' links_block  ;
links_block = '{' links_list '}'; 
links_list  = '' | link [',' [links_list]] ;
link        = Identifier ['?'] '->' rc_reference ;



rc_method = method_name [method_input] ['->' method_outputs] ';' ;
method_name = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE' ;
method_input = rc_type ['%'] ;
method_status = '#' Number ;
method_outputs = method_output [{',' method_output}] ;
method_output = method_status ':' rc_type | method_status | rc_type ; 


(* Entry Points *)
rc_entry_directive = 'entry' StringLiteral '->' rc_ident;