(* 
    =====
    Types
    =====
*)
type = (generic_identifier | struct | composite) type_operation; 

type_alias = 'type' generic_identifier '=' type ;

 
(* Struct literals *)

struct = struct_body [{ struct_mods }] ;
struct_mods = ',' ('in' | 'out') '+' struct_body ;

struct_body  = '{' [{ struct_field ^+ ',' }]  '}'     ;
struct_field = identifier ':' type                     ;


(* Composites *)
composite = c_array | c_tuple; 
c_array = type '[]' ;
c_tuple = '[' [{ type ^+ ',' }] ']' ; 


(* Type expressions *) 
type_operation = ['?'] ['%'];
(* Note that the lax operator '%' semantically must be applied to a struct *)
