identifier = /[a-zA-Z_]\w+/ - reserved;

(* Generics *)

generic_identifier  = identifier [ generic_params ]          ;
generic_params      =  '<' { generic_identifier ^ ',' } '>' ;


(* Imports *)
use = 'use' use_tree ;
use_tree = use_path '::' ( '*' | '{' [{ use_tree ^ ',' }] '}' | use_operand );

use_path = { identifier ^ '::'};
use_operand = Never 
(* Maybe later! 
    TAG: USE_ALIAS
    https://veneto.notion.site/Use-alias-ce0b472956d44607aa4c4e03bb5c1833
    use_operand = identifier ['as' identifier];  
*)


(* Top-level grammar *)
document = [{ 
    use | 
    (* Data *) type_alias | 
    (* API *) interface_decl | resource_class | rc_entry_directive
 }];